jasypt:
  encryptor:
    password: venkykey
server:
  port: 8082


spring:
  datasource:
    password: ''
    url: jdbc:mysql://127.0.0.1:3306/instagramclone
    username: root
  sql:
    init:
      mode: always



#spring.datasource.url=jdbc:mysql://sql110.epizy.com:3306/rfgd_20369548_instagramclone
#spring.datasource.username=rfgd_20369548
#spring.datasource.password=qwertykeypad
#pring.sql.init.mode=always
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#---- localhost of postgres using heroku postgres on cloud
#spring.datasource.url= jdbc:postgresql://ojyqmygfwrvzqo:1a4d585ebce8e6d0963414e4744dbccb5efd62b1c17f5b8ee49ef40091a31399@ec2-3-219-229-143.compute-1.amazonaws.com:5432/d51jl55em919q
#spring.datasource.username= ojyqmygfwrvzqo
#spring.datasource.password= 1a4d585ebce8e6d0963414e4744dbccb5efd62b1c17f5b8ee49ef40091a31399
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto= update